# Generated by Django 5.1.6 on 2025-02-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechadeentrega', models.DateField()),
                ('entregado', models.BooleanField(default=False)),
            ],
        ),
    ]
