# Generated by Django 5.1.6 on 2025-02-18 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_entregable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechadeentrega',
            new_name='fecha_de_entrega',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
